language: python
python: 3.7
dist: xenial
sudo: required

env:
  global:
    - PYPI_USERNAME=SethMichaelLarson
    # PYPI_PASSWORD is set in the Travis settings

install:
  - python -m pip install nox

stage: test
stages:
  - name: test
    if: type != cron
  - name: cron
    if: type = cron

jobs:
  include:
    - script: python -m nox -s check
    - script: python -m nox -s test

    - script: .travis/cron.sh
      stage: cron
